apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: # Add your image here
        ports:
        - containerPort: 8989
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            add: ["SYS_RESOURCE"]  # Allow container to adjust resource limits
        resources:
          requests:
            cpu: "250m"  # Reserve minimal CPU
            memory: "128Mi"  # Reserve minimal memory
          limits:
            cpu: "1"  # Allow up to 1 CPU
            memory: "512Mi"  # Allow up to 512Mi memory
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
      securityContext:
        fsGroup: 1000
      volumes:
      - name: proc
        hostPath:
          path: /proc
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: regcred
