apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: py-portfolio-hpa
  namespace: py-portfolio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: portfolio-deployment # Must match the deployment name
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30