apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  labels:
    app: portfolio
spec:
  ports:
    - port: 8989
      targetPort: 8989
      protocol: TCP
  selector:
    app: portfolio
  type: LoadBalancer
  loadBalancerIP: 192.168.1.210
